export enum ChallengeTypes {
  SMS_MFA = "SMS_MFA",
  SOFTWARE_TOKEN_MFA = "SOFTWARE_TOKEN_MFA",
  SELECT_MFA_TYPE = "SELECT_MFA_TYPE",
  MFA_SETUP = "MFA_SETUP",
  PASSWORD_VERIFIER = "PASSWORD_VERIFIER",
  CUSTOM_CHALLENGE = "CUSTOM_CHALLENGE",
  DEVICE_SRP_AUTH = "DEVICE_SRP_AUTH",
  DEVICE_PASSWORD_VERIFIER = "DEVICE_PASSWORD_VERIFIER",
  ADMIN_NO_SRP_AUTH = "ADMIN_NO_SRP_AUTH",
  NEW_PASSWORD_REQUIRED = "NEW_PASSWORD_REQUIRED",
}

export enum ChallengeResponseTypes {
  SMS_MFA_CODE = "SMS_MFA_CODE",
  PASSWORD = "PASSWORD",
  USERNAME = "USERNAME",
  PASSWORD_CLAIM_SIGNATURE = "PASSWORD_CLAIM_SIGNATURE",
  PASSWORD_CLAIM_SECRET_BLOCK = "PASSWORD_CLAIM_SECRET_BLOCK",
  TIMESTAMP = "TIMESTAMP",
  NEW_PASSWORD = "NEW_PASSWORD",
  SOFTWARE_TOKEN_MFA_CODE = "SOFTWARE_TOKEN_MFA_CODE",
  DEVICE_KEY = "DEVICE_KEY",
  SRP_A = "SRP_A",
  SECRET_HASH = "SECRET_HASH",
}

export enum AuthFlowTypes {
  USER_SRP_AUTH = "USER_SRP_AUTH",
  REFRESH_TOKEN_AUTH = "REFRESH_TOKEN_AUTH",
  REFRESH_TOKEN = "REFRESH_TOKEN",
  CUSTOM_AUTH = "CUSTOM_AUTH",
  ADMIN_NO_SRP_AUTH = "ADMIN_NO_SRP_AUTH",
  USER_PASSWORD_AUTH = "USER_PASSWORD_AUTH",
  ADMIN_USER_PASSWORD_AUTH = "ADMIN_USER_PASSWORD_AUTH",
}

export enum DeliveryMediumTypes {
  SMS = "SMS",
  EMAIL = "EMAIL",
}

export enum Actions {
  CREATE_USER = 1,
  DELETE_USER,
  AUTH_USER,
  AUTH_NEW_PASSWORD,
  DECODE_ACCESS_TOKEN,
  DECODE_ID_TOKEN,
  EXIT,
}
